Revert "storage: deflake TestIntegration_UpdateRetentionPolicy by 1 bucket use"
This reverts commit fff13f4acecfc35176a1dd0e3664900ca6795705.

Reason for revert: This integration test consistently fails in Kokoro when re-enabled. Need to debug failure before merging again.

=== RUN   TestIntegration_UpdateRetentionPolicy
    TestIntegration_UpdateRetentionPolicy: integration_test.go:2641: input: <nil>
        got=-, want=+:
          (*storage.RetentionPolicy)(
        - 	nil,
        + 	&{RetentionPeriod: s"1m0s"},
          )
--- FAIL: TestIntegration_UpdateRetentionPolicy (7.98s)

Updates #1959
Updates #1632

Change-Id: I550a971dcd569f45ace508f56dc928ab38f2a19d
Reviewed-on: https://code-review.googlesource.com/c/gocloud/+/55410
Reviewed-by: kokoro <noreply+kokoro@google.com>
Reviewed-by: Cody Oss <codyoss@google.com>